# Base blog settings
baseurl                      : '' # the subpath of your site,                         # e.g. /blog/
                              # set to '' in case of hosting on GitHub
url                          : "http://xl402.github.io" # the base hostname & protocol for your site
                                  # `http://<username>.github.io` - for GitHub

blog:
  title                      : Lu Blog
  description                  : >
                               © 2020. Powered by Jekyll & Dactl

# Layout configuration
  logo_path                  : #"assets/img/dactl.svg" # path to logo file
  search_path                : "https://xl402.github.io"
  hero_layout                : true # turn on hero layout for blog and posts
  hero_placeholder           : "assets/img/generic_hero.jpg" # placeholder for hero image
  excerpts                   : true # show excerpts instead of full post content on blog page
  inline_footnotes           : true # enable/disable barefoot inline footnotes
  titles_only                : false # show post titles only on main blog page

# Fonts
  font                       : '"Rubik", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
  load_google_fonts          : 'Rubik:400,400italic,700,700italic'


# Author info
author:
  fullname                  : Tom Lu
  rss                       : false # generate RSS feed and show it's icon in header
  mail                      : #https://www.linkedin.com/in/tomlu97/ #your@email.com # change to your e-mail address
  twitter                   : # twitter-user-name
  github                    : xl402
  youtube                   : #youtube-user-name
  stackoverflow             : tomlu97 #stackoverflow-user-name
  disqus                    : # dactl # your disqus site name
  google_analytics          : # 'UA-XXXXXXXX-X'
  linkedin                  : tomlu
  photo                     : "uploads/me.png"
  photo2x                   : "uploads/me2.png"




## !!
## Advanced blog settings
## You should not change anything here unless you know what you are doing

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Permalinks
permalink                    : posts/:slug

# Posts
excerpt_separator            : <!–-break-–>

# Pagination
paginate                     : 5
paginate_path                : '/page-:num/'

# Tags
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog-by-tag

# Handling Reading
exclude                    : ["README.md", "README.html"]

# https://github.com/jekyll/jekyll/issues/4619
# Markdown and highlighter settings


# Sass settings
sass:
  sass_dir                : _sass
  style                   : compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings               : all
  endings                 : all
  comments                : ["<!-- ", " -->"]
  blanklines              : true
  profile                 : false
  ignore:
  envs                    : [local]
